name: deploy-azure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "dev or prod"
        required: true
        default: "dev"
      resourceGroup:
        description: "Azure resource group name"
        required: true
      location:
        description: "Azure location"
        required: true
        default: "brazilsouth"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy infra (Bicep)
        run: |
          az deployment sub create \
            --location "${{ inputs.location }}" \
            --template-file infra/azure/subscription.bicep \
            --parameters resourceGroupName="${{ inputs.resourceGroup }}" \
            --parameters location="${{ inputs.location }}" \
            --parameters env="${{ inputs.environment }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install functions deps
        working-directory: apps/functions
        run: npm install

      - name: Deploy Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: apps/functions
